---
groups:
  - name: cli
    jobs:
    - unit-tests-linux
    - build-linux32
    - build-linux64
    - build-win32
    - build-win64
    - build-osx
    - cats-win64
  - name: bump
    jobs:
    - patch-bump
    - pre-bump

resources:
- name: cli
  type: git
  source:
    uri: git@github.com:cloudfoundry/cli
    private_key: {{cf-cli-eng-github-private-key}}
    branch: concourse-reloaded

- name: cf-release
  type: git
  source:
    uri: git@github.com:krishicks/cf-release
    private_key: {{cf-cli-eng-github-private-key}}
    branch: windows-delete-fix

- name: cf-acceptance-tests
  type: git
  source:
    uri: git@github.com:cloudfoundry/cf-acceptance-tests
    private_key: {{cf-cli-eng-github-private-key}}
    branch: dont-delete-app-file-105779022

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/cli
    private_key: {{cf-cli-eng-github-private-key}}
    branch: version
    file: VERSION

- name: linux32-binary
  type: s3
  source:
    bucket: cf-cli-pipeline-artifacts
    regexp: linux32-binary-(.*)
    access_key_id: {{pipeline-bucket-access-key-id}}
    secret_access_key: {{pipeline-bucket-secret-access-key}}

- name: linux64-binary
  type: s3
  source:
    bucket: cf-cli-pipeline-artifacts
    regexp: linux64-binary-(.*)
    access_key_id: {{pipeline-bucket-access-key-id}}
    secret_access_key: {{pipeline-bucket-secret-access-key}}

- name: win32-binary
  type: s3
  source:
    bucket: cf-cli-pipeline-artifacts
    regexp: win32-binary-(.*).exe
    access_key_id: {{pipeline-bucket-access-key-id}}
    secret_access_key: {{pipeline-bucket-secret-access-key}}

- name: win64-binary
  type: s3
  source:
    bucket: cf-cli-pipeline-artifacts
    regexp: win64-binary-(.*).exe
    access_key_id: {{pipeline-bucket-access-key-id}}
    secret_access_key: {{pipeline-bucket-secret-access-key}}

- name: osx-binary
  type: s3
  source:
    bucket: cf-cli-pipeline-artifacts
    regexp: osx-binary
    access_key_id: {{pipeline-bucket-access-key-id}}
    secret_access_key: {{pipeline-bucket-secret-access-key}}

jobs:
- name: patch-bump
  plan:
  - put: version
    params: {bump: patch}

- name: pre-bump
  plan:
  - put: version
    params: {pre: rc}

- name: unit-tests-linux
  public: true
  plan:
  - get: cli
    trigger: true
  - task: unit-tests
    file: cli/ci/unit.linux.yml

- name: build-linux64
  public: true
  plan:
  - get: cli
    trigger: false
    passed: [unit-tests-linux]
  - get: version
    trigger: true
  - task: build
    config:
      platform: linux
      image: docker:///cloudfoundry/cli-ci
      inputs:
      - name: cli
        path: gopath/src/github.com/cloudfoundry/cli
      - name: version
      run:
        path: bash
        args:
        - -c
        - |
          set -ex

          export GOPATH=$PWD/gopath
          export PATH=$GOPATH/bin:$PATH

          cd $GOPATH/src/github.com/cloudfoundry/cli

          bin/replace-sha
          bin/generate-language-resources

          export GODEP_GOPATH=$PWD/Godeps/_workspace
          export GOPATH=$GODEP_GOPATH:$GOPATH

          GOARCH= GOOS=linux go build -o out/cf ./main
  - put: linux64-binary
    params:
      from: build/gopath/src/github.com/cloudfoundry/cli/out/cf
      to: linux64-binary

- name: build-linux32
  public: true
  plan:
  - get: cli
    trigger: false
    passed: [unit-tests-linux]
  - get: version
    trigger: true
  - task: build
    config:
      platform: linux
      image: docker:///cloudfoundry/cli-ci
      inputs:
      - name: cli
        path: gopath/src/github.com/cloudfoundry/cli
      run:
        path: bash
        args:
        - -c
        - |
          set -ex

          export GOPATH=$PWD/gopath
          export PATH=$GOPATH/bin:$PATH

          cd $GOPATH/src/github.com/cloudfoundry/cli

          bin/replace-sha
          bin/generate-language-resources

          export GODEP_GOPATH=$PWD/Godeps/_workspace
          export GOPATH=$GODEP_GOPATH:$GOPATH

          GOARCH=386 GOOS=linux go build -o out/cf ./main
  - put: linux32-binary
    params:
      from: build/gopath/src/github.com/cloudfoundry/cli/out/cf
      to: linux32-binary

- name: build-win32
  public: true
  plan:
  - get: cli
    trigger: false
    passed: [unit-tests-linux]
  - get: version
    trigger: true
  - task: build
    config:
      platform: linux
      image: docker:///cloudfoundry/cli-ci
      inputs:
      - name: cli
        path: gopath/src/github.com/cloudfoundry/cli
      run:
        path: bash
        args:
        - -c
        - |
          set -ex

          export GOPATH=$PWD/gopath
          export PATH=$GOPATH/bin:$PATH

          cd $GOPATH/src/github.com/cloudfoundry/cli

          bin/replace-sha
          bin/generate-language-resources

          export GODEP_GOPATH=$PWD/Godeps/_workspace
          export GOPATH=$GODEP_GOPATH:$GOPATH

          GOARCH=386 GOOS=windows go build -o out/cf.exe ./main
  - put: win32-binary
    params:
      from: build/gopath/src/github.com/cloudfoundry/cli/out/cf.exe
      to: win32-binary.exe

- name: build-win64
  public: true
  plan:
  - get: cli
    trigger: false
    passed: [unit-tests-linux]
  - get: version
    trigger: true
  - task: build
    config:
      platform: linux
      image: docker:///cloudfoundry/cli-ci
      inputs:
      - name: cli
        path: gopath/src/github.com/cloudfoundry/cli
      run:
        path: bash
        args:
        - -c
        - |
          set -ex

          export GOPATH=$PWD/gopath
          export PATH=$GOPATH/bin:$PATH

          cd $GOPATH/src/github.com/cloudfoundry/cli

          bin/replace-sha
          bin/generate-language-resources

          export GODEP_GOPATH=$PWD/Godeps/_workspace
          export GOPATH=$GODEP_GOPATH:$GOPATH

          GOARCH=amd64 GOOS=windows go build -o out/cf.exe ./main
  - put: win64-binary
    params:
      from: build/gopath/src/github.com/cloudfoundry/cli/out/cf.exe
      to: win64-binary.exe

- name: build-osx
  public: true
  plan:
  - get: cli
    trigger: false
    passed: [unit-tests-linux]
  - get: version
    trigger: true
  - task: build
    config:
      platform: linux
      image: docker:///cloudfoundry/cli-ci
      inputs:
      - name: cli
        path: gopath/src/github.com/cloudfoundry/cli
      run:
        path: bash
        args:
        - -c
        - |
          set -ex

          export GOPATH=$PWD/gopath
          export PATH=$GOPATH/bin:$PATH

          cd $GOPATH/src/github.com/cloudfoundry/cli

          bin/replace-sha
          bin/generate-language-resources

          export GODEP_GOPATH=$PWD/Godeps/_workspace
          export GOPATH=$GODEP_GOPATH:$GOPATH

          GOARCH=amd64 GOOS=darwin go build -o out/cf ./main
  - put: osx-binary
    params:
      from: build/gopath/src/github.com/cloudfoundry/cli/out/cf
      to: osx-binary

- name: cats-win64
  public: true
  plan:
  - aggregate:
    - get: cf-release
      trigger: true
    - get: cf-acceptance-tests
      trigger: true
    - get: cli
      trigger: false
    - get: win64-binary
      trigger: true
      passed: [build-win64]
  - task: cats
    path: ci/cats.windows.yml
    params:
      BOSH_LITE_IP: {{bosh-lite-ip-windows}}
